from slrp import RE

INTEGER_OPERAND = RE(r"(\d+)")
OPERATOR = RE("([-+/*])")
WHITESPACE = RE(r"\s*")
APPLIED_OPERATOR = WHITESPACE * OPERATOR * WHITESPACE * INTEGER_OPERAND
BINARY_OPERATION = (INTEGER_OPERAND * WHITESPACE) + APPLIED_OPERATOR
